export const AUTH = 'AUTH';
export const VET_AUTH = 'VET_AUTH';
export const LOGOUT = 'LOGOUT';
export const VERIFY = 'VERIFY';

export const GET_ALL_VETS = 'GET_ALL_VETS';
export const GET_ALL_USER_PETS = 'GET_ALL_USER_PETS';
export const GET_ALL_USER_APPOINTMENTS = 'GET_ALL_USER_APPOINTMENTS';
export const GET_ALL_VET_APPOINTMENTS = 'GET_ALL_VET_APPOINTMENTS';
export const GET_APPOINTMENTS_BY_STATUS = 'GET_APPOINTMENTS_BY_STATUS';
